export const authActions = {
  USER_SIGNUP_INITIATE: 'USER_SIGNUP_INITIATE',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

  USER_SIGNIN_INITIATE: 'USER_SIGNIN_INITIATE',
  USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
  USER_SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',

}

export const boardActions = {
  GET_ALL_BOARDS_INIITIATE: 'GET_ALL_BOARDS_INIITIATE',
  GET_ALL_BOARDS_SUCCESS: 'GET_ALL_BOARDS_SUCCESS',
  GET_ALL_BOARDS_FAILURE: 'GET_ALL_BOARDS_FAILURE',

  GET_BOARD_BY_ID_INITIATE: 'GET_BOARD_BY_ID_INITIATE',
  GET_BOARD_BY_ID_SUCCESS: 'GET_BOARD_BY_ID_SUCCESS',
  GET_BOARD_BY_ID_FAILURE: 'GET_BOARD_BY_ID_FAILURE',

  CREATE_BOARD_INITIATE: 'CREATE_BOARD_INITIATE',
  CREATE_BOARD_SUCCESS: 'CREATE_BOARD_SUCCESS',
  CREATE_BOARD_FAILURE: 'CREATE_BOARD_FAILURE',

}